on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Clone
        id: clone
        uses: actions/checkout@HEAD
      - name: Run the action
        id: hello
        uses: Ale0x78/effective-spork@HEAD
